websoc:
    baseUrl: https://www.reg.uci.edu/perl/WebSoc
    formUrl: form
    searchUrl: search
    searchFragment: resources/templates/fragments/search.html
    formFragment: resources/templates/fragments/form.html

cassandra:
    contactPoints: 192.168.0.10
    keyspace: antreminder
    port: 9042
app:
    encoding: UTF-8
