websoc:
    baseUrl: https://www.reg.uci.edu/perl/WebSoc
    formUrl: form
    searchUrl: search
    cacheSearchPage: resources/templates/websoc/search.html
    cacheSearchForm: resources/templates/websoc/form.html

cassandra:
    contactPoints: 192.168.0.10
    keyspace: antreminder
    port: 9042
app:
    encoding: UTF-8
