websoc:
    baseUrl: https://www.reg.uci.edu/perl/WebSoc
    formUrl: /schedule
    searchUrl: /schedule
    searchFragment: resources/templates/fragments/schedule/search.html
    formFragment: resources/templates/fragments/schedule/form.html
reminders:
    url: /reminders
cassandra:
    contactPoints: 192.168.0.10
    keyspace: antreminder
    port: 9042
app:
    encoding: UTF-8
