# TODO: clean

application.name: AntReminder
application.mode: dev


security.basic.enabled: false
html: text/html


websoc:
    baseUrl: https://www.reg.uci.edu/perl/WebSoc
    formUrl: /schedule
    searchUrl: /schedule
    searchFragment: resources/templates/fragments/schedule/search.html
    formFragment: resources/templates/fragments/schedule/form.html

schedule.url: /schedule

reminders:
    url: /reminders
    add: /reminders/add
    get: /reminders/get
    getall: /reminders/getall



api.reminders.url: http://localhost:2424/reminder
api:
  reminders:
    url:
      get: /get
      getall: /getall
      add: /add

app:
    encoding: UTF-8
