server:
    port: ${port:8080}

app:
    name: AntReminder
    host: localhost:${server.port}
    encoding: UTF-8

security.basic.enabled: false
html: text/html
server.error.whitelabel.enabled: false

websoc:
    baseUrl: https://www.reg.uci.edu/perl/WebSoc
    formUrl: /schedule
    searchUrl: /schedule
    searchFragment: resources/templates/fragments/schedule/search.html
    formFragment: resources/templates/fragments/schedule/form.html

schedule.url: /schedule

reminders:
    url: /reminders
    add: /reminders/add
    get: /reminders/get
    getall: /reminders/getall

spring:
    datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.15:3306/test_csthings
        username: root
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    entitymanager:
        packagesToScan: net.csthings.antreminder.entity.dto
