server:
    port: 8080

app:
    name: AntReminder
    host: localhost:8080
    encoding: UTF-8

security.basic.enabled: false
html: text/html
server.error.whitelabel.enabled: false

websoc:
    baseUrl: https://www.reg.uci.edu/perl/WebSoc

logging:
    path: logs
    file: antreminder.log

reminder:
    runner:
        scan-interval: 5000 #Milliseconds
        scan-url: https://www.reg.uci.edu/perl/WebSoc
        scan-expected-title: Schedule of Classes search results

mail:
    name: AntReminder Support
    email: antreminder-support@csthings.net
    key: dummy-test-key

spring:
    thymeleaf.cache: false
    datasource:
        driver: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.2:3306/test_antreminder?verifyServerCertificate=false&useSSL=false&requireSSL=false
        username: antreminder
        password: antreminder
        testWhileIdle: true
        validationQuery: SELECT 1
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    entitymanager:
        packagesToScan: net.csthings.antreminder.entity.dto
    cache:
        cache-names: validation_account, reminders, email_account
        guava:
            spec:
                maximumSize: 500
                expireAfterAccess: 30m
